export default {
  avatar: () => import('./avatar.svg'),
  brokenImage: () => import('./brokenImage.svg'),
  check: () => import('./check.svg'),
  close: () => import('./close.svg'),
  chevronUp: () => import('./chevronUp.svg'),
  chevronDown: () => import('./chevronDown.svg'),
  chevronRight: () => import('./chevronRight.svg'),
  chevronLeft: () => import('./chevronLeft.svg'),
  delete: () => import('./delete.svg'),
  // draft: () => import('./draft.svg'),
  externalLink: () => import('./externalLink.svg'),
  fullscreen: () => import('./fullscreen.svg'),
  fullscreenExit: () => import('./fullscreenExit.svg'),
  gear: () => import('./gear.svg'),
  loader: () => import('./loader.svg'),
  menu: () => import('./menu.svg'),
  mic: () => import('./mic.svg'),
  moreVertical: () => import('./moreVertical.svg'),
  moreHorizontal: () => import('./moreHorizontal.svg'),
  plus: () => import('./plus.svg'),
  redo: () => import('./redo.svg'),
  undo: () => import('./undo.svg'),
  requiredStar: () => import('./requiredStar.svg'),
  send: () => import('./send.svg'),
  settings: () => import('./settings.svg'),
};
