export default {
  avatar: () => import('./avatar.svg'),
  brokenImage: () => import('./brokenImage.svg'),
  check: () => import('./check.svg'),
  close: () => import('./close.svg'),
  chevronUp: () => import('./chevronUp.svg'),
  chevronDown: () => import('./chevronDown.svg'),
  chevronRight: () => import('./chevronRight.svg'),
  chevronLeft: () => import('./chevronLeft.svg'),
  delete: () => import('./delete.svg'),
  externalLink: () => import('./externalLink.svg'),
  fullscreen: () => import('./fullscreen.svg'),
  fullscreenExit: () => import('./fullscreenExit.svg'),
  menu: () => import('./menu.svg'),
  mic: () => import('./mic.svg'),
  moreVertical: () => import('./moreVertical.svg'),
  moreHorizontal: () => import('./moreHorizontal.svg'),
  plus: () => import('./plus.svg'),
  requiredStar: () => import('./requiredStar.svg'),
};
