import react from '@vitejs/plugin-react-swc';
import { createHash } from 'crypto';
import { existsSync, readFileSync, writeFileSync } from 'fs';
import { basename, relative } from 'path';
import postcssPresetEnv from 'postcss-preset-env';
import { type Plugin, defineConfig } from 'vite';
import svgr from 'vite-plugin-svgr';

import pkg from '../../../package.json';
import paths from './paths';

const STYL_MODULE_QUERY = '?lang.module.styl';
const RAW_LOADER_PREFIX = '!!raw-loader!';

/**
 * Every `.styl` file is a CSS module (no `.module.styl` suffix), but Vite only
 * treats `*.module.*` ids as modules. Tag resolved `.styl` imports with a query
 * ending in `.module.styl` so Vite's CSS-modules check matches while the id
 * still points at the real file (HMR and file reads use the path before `?`).
 * The query starts with a word character on purpose: Vite's timestamp strip
 * (`/\bt=\d{13}&?\b/`) turns `?t=…&.module.styl` into `?&.module.styl`, a
 * second module for the same file, and CSS HMR then goes stale or reloads.
 */
function stylusModules(): Plugin {
  return {
    name: 'uilib:stylus-modules',
    enforce: 'pre',
    async resolveId(source, importer, options) {
      if (!importer || !/\.styl$/.test(source)) return null;
      const resolved = await this.resolve(source, importer, {
        ...options,
        skipSelf: true,
      });
      if (!resolved || resolved.external || resolved.id.includes('?')) {
        return resolved;
      }
      return { ...resolved, id: `${resolved.id}${STYL_MODULE_QUERY}` };
    },
  };
}

/**
 * `import code from '!!raw-loader!./Example'` → file contents as a string.
 * Resolves the path like any other import, then hands it to Vite's `?raw`.
 */
function rawLoader(): Plugin {
  return {
    name: 'uilib:raw-loader',
    enforce: 'pre',
    async resolveId(source, importer, options) {
      if (!source.startsWith(RAW_LOADER_PREFIX)) return null;
      const resolved = await this.resolve(
        source.slice(RAW_LOADER_PREFIX.length),
        importer,
        { ...options, skipSelf: true }
      );
      if (!resolved) return null;
      return `${resolved.id.split('?')[0]}?raw`;
    },
  };
}

/** `React` is used as a global in some files (webpack `ProvidePlugin`). */
function provideReact(): Plugin {
  const hasReactBinding = /\bimport\s+(type\s+)?(\*\s+as\s+)?React\b/;
  return {
    name: 'uilib:provide-react',
    enforce: 'pre',
    transform(code, id) {
      if (id.includes('?') || !id.startsWith(paths.src)) return null;
      if (!/\.[jt]sx?$/.test(id) || id.endsWith('.d.ts')) return null;
      if (!/\bReact\b/.test(code) || hasReactBinding.test(code)) return null;
      // Same line, so line numbers in stack traces stay correct.
      return { code: `import React from 'react';${code}`, map: null };
    },
  };
}

/** `[name]__[local]___[hash:base64:5]`, as css-loader produced it under webpack. */
function scopedName(local: string, filename: string) {
  const file = filename.split('?')[0];
  const name = basename(file).replace(/\.[^.]+$/, '');
  const hash = createHash('md5')
    .update(`${relative(paths.src, file)}\0${local}`)
    .digest('base64url')
    .slice(0, 5);
  return `${name}__${local}___${hash}`;
}

/**
 * Keep `Foo.styl.d.ts` class typings in sync (what css-modules-typescript-loader
 * did under webpack). Rewrites only when the set of class names changed.
 */
function writeStylTypings(cssFileName: string, json: Record<string, string>) {
  const dts = `${cssFileName.split('?')[0]}.d.ts`;
  const keys = Object.keys(json).sort();
  const existing = existsSync(dts)
    ? [...readFileSync(dts, 'utf8').matchAll(/^\s+'?([^':\s]+)'?: string;$/gm)]
        .map(m => m[1])
        .sort()
    : null;
  if (existing && existing.join('\n') === keys.join('\n')) return;
  writeFileSync(
    dts,
    [
      '// This file is automatically generated.',
      '// Please do not change this file!',
      'interface CssExports {',
      ...keys.map(k => `  '${k}': string;`),
      '}',
      'export const cssExports: CssExports;',
      'export default cssExports;',
      '',
    ].join('\n')
  );
}

/** Build only: stats snippet at the end of <body> (was html-webpack-partials-plugin). */
function analytics(): Plugin {
  return {
    name: 'uilib:analytics',
    apply: 'build',
    transformIndexHtml(html) {
      const snippet = readFileSync(`${paths.assets}/analytics.html`, 'utf8');
      return html.replace('</body>', `${snippet}</body>`);
    },
  };
}

/** Build only: rasterize favicons + web manifest into `assets/` and inject their tags. */
function favicons(): Plugin {
  const prefix = 'assets/';
  let response: {
    images: { name: string; contents: Buffer }[];
    files: { name: string; contents: string }[];
    html: string[];
  } | null = null;

  return {
    name: 'uilib:favicons',
    apply: 'build',
    async buildStart() {
      const { favicons: generate } = await import('favicons');
      response = await generate(`${paths.assets}/logo.svg`, {
        path: prefix,
        appName: 'UILIB',
        developerName: 'Oleh Apostol',
        developerURL: null,
        background: '#fff',
        theme_color: '#1a1a1a',
        display: 'standalone',
        icons: {
          android: true,
          appleIcon: true,
          appleStartup: false,
          favicons: true,
          windows: true,
          yandex: false,
        },
      });
    },
    generateBundle() {
      for (const { name, contents } of [
        ...response.images,
        ...response.files,
      ]) {
        this.emitFile({
          type: 'asset',
          fileName: `${prefix}${name}`,
          source: contents,
        });
      }
    },
    transformIndexHtml(html) {
      return html.replace('</head>', `${response.html.join('')}</head>`);
    },
  };
}

export default defineConfig(({ mode }) => {
  const isDev = mode === 'development';

  return {
    publicDir: false,

    resolve: {
      // webpack `resolve.modules: [src, docs]` — bare imports used in the code
      alias: {
        uilib: paths.src,
        docs: paths.docs,
        helpers: `${paths.docs}/helpers`,
        theme: `${paths.src}/theme.styl`,
      },
      // lucide-react ships a nested react; force one copy so its hooks share the app dispatcher
      dedupe: ['react', 'react-dom'],
    },

    define: {
      isDEV: JSON.stringify(isDev),
      VERSION: JSON.stringify(pkg.version),
    },

    css: {
      modules: {
        generateScopedName: scopedName,
        getJSON: isDev ? writeStylTypings : undefined,
      },
      preprocessorOptions: {
        // `@import 'theme'` resolves against src/ (webpack resolve.modules).
        // Vite looks options up by file extension, so `.styl` reads `styl`.
        styl: { paths: [paths.src, paths.docs] },
      },
      postcss: {
        // Autoprefixer is on by default in postcss-preset-env. Cast: it is
        // typed against the root postcss, Vite against its own nested copy.
        plugins: [postcssPresetEnv({ stage: 3 }) as any],
      },
    },

    plugins: [
      stylusModules(),
      rawLoader(),
      provideReact(),
      svgr({
        include: '**/*.svg',
        svgrOptions: { icon: true },
      }),
      react(),
      analytics(),
      favicons(),
    ],

    server: {
      port: 8181,
    },

    build: {
      outDir: paths.build,
      emptyOutDir: true,
      sourcemap: false,
      // Internal docs site: the main bundle and lazy example pages are large
      // by design; keep the warning for real regressions only.
      chunkSizeWarningLimit: 1500,
      rollupOptions: {
        // Example scopes (`import * as helpers`) go through justorm's store
        // proxy, which breaks on frozen namespace objects.
        output: { freeze: false },
      },
    },
  };
});
